[tool.black]
line-length = 75
target-version = ["py37", "py38", "py39", "py310"]
extend-exclude = "__init__.py, asgi.py, wsgi.py"
exclude = "postgres_data/*"

[tool.flake8]
max-line-length = 75
max-complexity = 6
ignore = "D100,D104,D401,W504,RST303,RST304,DAR103,DAR203"

[tool.isort]
profile = "black"
