version: '3.8'

services:
  tests:
    container_name: twitter_clone_tests
    build: ../tests
    depends_on:
      - db
    networks:
      - app-network
    volumes:
      - ../tests:/tests
    working_dir: /tests
    command: ["sh", "-c", "sleep 4 && pytest --cov=../tests"]

  web:
    env_file:
      - .env
    container_name: twitter_clone_web
    build: ../app
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - app-network
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - DATABASE_URL=${DATABASE_URL}
    working_dir: /api
    command: ["sh", "-c", "sleep 10 && uvicorn start:app --host 0.0.0.0 --port 8000 --reload"]

  db:
    env_file:
      - .env
    image: postgres
    container_name: twitter_clone_db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - app-network
    command: [ "postgres" ]


volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge